### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by melodien** [NanoCAN/SAVANAH#7]
When I try to upload a file, I get the message "you are not authorized to view this page".

**Comment by mlist** [comment]
Thanks for trying SAVANAH. Someone has messed with the demo system user. File upload should now work again, at least it did for a test library I just added. 

A general note: the library file upload features takes a long time if it involves many plates and is a bit error-prone if the input files don't follow the proposed format to the letter . Please get in touch should you have issues with getting your file to work.
